### PR TITLE
Run auto-formatter

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
As promised :)

### CODE REVIEW

**Comment by MommyHeather** [comment]
How does this particular auto-formatter work - would it be something I can automate as an on-push thing?


Also - I think method calls / definitions that have any arguments should have spaces between the parentheses. Can that be done at all?

**Comment by HoldYourWaffle** [comment]
> How does this particular auto-formatter work - would it be something I can automate as an on-push thing?

This was the IDEA autoformatter with mostly-default settings. I doubt you could integrate that one, but there's definitely something for that. However, in my experience it's usually much easier to just configure your IDE to format on save than to fiddle around with git hooks.

> Also - I think method calls / definitions that have any arguments should have spaces between the parentheses. Can that be done at all?

Probably, I'll take a look, though it's not a common stylistic choice as far as I know.

**Comment by MommyHeather** [comment]
Alright. No rush, as I'd need to review this on desktop anyway and I've no clue when I'll get the chance

**Comment by HeatherComputer** [comment]
Desktop review, complete

I'll merge this for now, as it's just formatting changes and largely they *are* beneficial.
However, when things are merged into one branch, this will need to be reran and ideally we'll setup an actual to keep a consistent code style - including stuff that the formatter here didn't handle.

**Pull request merged**
